[tool.poetry]
name = "net2cog"
version = "1.4.0a0"
description = "NetCDF to COG Conversion Service"
authors = ["podaac <podaac@jpl.nasa.gov>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/podaac/net2cog"
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules"
]
exclude = ['contrib', 'docs', 'tests']
packages = [
    { include = "net2cog" },
]

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
boto3 = "^1.42.73"
requests = "^2.33.0"
netcdf4 = "^1.7.4"
xarray = "^2026.2.0"
rio-cogeo = "^7.0.1"
rasterio = "^1.5.0"
rioxarray = "^0.22.0"
numpy = "^2.4.3"
harmony-service-lib = "2.11.0"
dask = "^2026.3.0"
h5netcdf = "^1.8.1"
h5py = "^3.16.0"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.2"
flake8 = "^7.3.0"
pytest-cov = "^7.1.0"
pylint = "^4.0.5"
sphinx = "^9.1.0"
coverage = "^7.13.5"

[tool.poetry.extras]
harmony = ["harmony-service-lib"]

[tool.poetry.scripts]
net2cog_harmony = 'net2cog.netcdf_convert_harmony:main'

[tool.coverage.run]
source = ['net2cog']
relative_files = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

